Switch to Docker actions

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -19,23 +19,30 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       -
+        name: Checkout
+        uses: actions/checkout@v2.3.2
+      -
         name: Prepare
-        id: prepare
+        id: prep
         run: |
           echo ::set-output name=build_tag::test
           echo ::set-output name=service_name::swarm-cronjob
           echo ::set-output name=running_timeout::120
           echo ::set-output name=running_log_check::Number of cronjob tasks: 6
       -
-        name: Checkout
-        uses: actions/checkout@v2.3.2
+        name: Set up QEMU
+        uses: docker/setup-qemu-action@v1
       -
         name: Set up Docker Buildx
-        uses: crazy-max/ghaction-docker-buildx@v3.3.0
+        uses: docker/setup-buildx-action@v1
       -
-        name: Docker Buildx
-        run: |
-          docker buildx build --load --tag ${{ steps.prepare.outputs.build_tag }} --file Dockerfile .
+        name: Build
+        uses: docker/build-push-action@v2
+        with:
+          context: .
+          file: ./Dockerfile
+          load: true
+          tags: ${{ steps.prep.outputs.build_tag }}
       -
         name: Swarm init
         run: |
@@ -53,26 +60,26 @@ jobs:
       -
         name: Create service
         run: |
-          docker service create --name ${{ steps.prepare.outputs.service_name }} \
+          docker service create --name ${{ steps.prep.outputs.service_name }} \
             --mount type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock \
             --env "LOG_LEVEL=debug" \
             --env "LOG_JSON=false" \
             --constraint 'node.role == manager' \
-            ${{ steps.prepare.outputs.build_tag }}
+            ${{ steps.prep.outputs.build_tag }}
       -
         name: Test service
         run: |
-          TIMEOUT=$((SECONDS + ${{ steps.prepare.outputs.running_timeout }}))
+          TIMEOUT=$((SECONDS + ${{ steps.prep.outputs.running_timeout }}))
           while read LOGLINE; do
             echo ${LOGLINE}
-            if [[ ${LOGLINE} == *"${{ steps.prepare.outputs.running_log_check }}"* ]]; then
+            if [[ ${LOGLINE} == *"${{ steps.prep.outputs.running_log_check }}"* ]]; then
               echo "🎉 Service up!"
               break
             fi
             if [[ $SECONDS -gt ${TIMEOUT} ]]; then
-              >&2 echo "❌ Failed to run ${{ steps.prepare.outputs.service_name }} service"
+              >&2 echo "❌ Failed to run ${{ steps.prep.outputs.service_name }} service"
               docker swarm leave --force > /dev/null 2>&1 || true
               exit 1
             fi
-          done < <(docker service logs -f ${{ steps.prepare.outputs.service_name }} 2>&1)
+          done < <(docker service logs -f ${{ steps.prep.outputs.service_name }} 2>&1)
           docker swarm leave --force > /dev/null 2>&1 || true
